<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class simpandatapersmt extends Model
{
    protected $table = 'simpan_persmt';

    protected $fillable = [
        'id',
        'user_id',
        'unit',
        'semester',
        'tahun',
        'jenjang_pendidikan',
        'pelatihan_khusus',
        'seminar_diluar_pln',
        'kemampuan_masalah',
        'kemampuan_rekomendasi',
        'kerjasama_tim',
        'emosional',
        'berarti',
        'bagian',
        'masalah_pln',
        'batas_normal',
        'tinggal_komitmen',
        'loyalitas',
        'luar_biasa_kesuksesan_ai',
        'saya_ai_pln',
        'inspirasi_kerja_terbaik',
        'perkembangan_ai',
        'ai_profesi_terbaik',
        'maksimal_hasil_terbaik',
        'tugas_tepat_waktu',
        'dekat_ke_atasan',
        'saran_membangun',
        'terbaik_daripada_rekan',
        'evaluasi_selalu_memuaskan',
        'respect_pada_saya',
        'hubungan_baik_auditee',
        'tidak_melanggar_aturan',
        'kesesuaian_tugas',
        'diterima_wajar',
        'tugas_tidak_wajar',
        'sd_cukup',
        'puas_gaji',
        'suka_pekerjaan',
        'tidak_ingin_pindah',
        'suka_daripada_teman',
        'promosi',
        'puas_penilaian_kinerja_ai',
        'puas_pengelolaan_karir_ai',
        'rotasi_pegawai_ai',
        'keluhan',
        'saran',
        'kons1',
        'kons2',
        'kons3',
        'kons4',
        'kons5',
        'struct1',
        'struct2',
        'struct3',
        'time1',
        'time2',
        'time3',
        'kinerja1',
        'kinerja2',
        'kinerja3',
        'intent1',
        'intent2',
        'intent3',
        'intent4',
        'promo1',
        'promo2',
        'promo3',
        'komunikasi1',
        'komunikasi2',
        'komunikasi3',
        'komunikasi4',
        'cworker1',
        'cworker2',
        'cworker3',
        'cworker4',
    ];
}
